config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get '/auth/facebook/callback' => 'sessions#facebook'

  delete "/logout", to: "sessions#destroy", as: "logout"

  resources :food_banks do
    resources :orders_as_admin, only: [:index, :new, :create]
  end

  resources :orders_as_admin

  resources :users, only: [] do
    resources :orders
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_bank.rb
class FoodBank < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders
    # Joins with orders to bring in that collection where orders.created at orders.created_at
    scope :todays_orders, -> { joins(:orders).where("orders.created_at > ?", 1.days.ago) }
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :food_bank

    validates_presence_of :protein, :vegetable, :fruit, :grain, :dairy, :dessert


end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders
    has_many :food_banks, through: :orders

    validates :email, presence: true, uniqueness: true
    has_secure_password

    # scope :most_recent_order, -> { self.orders.order(created_at: :desc LIMIT 1) }

    def self.find_or_create_from_omniauth(user_info)
        User.first_or_create(uid: user_info["uid"]) do |user|
            user.email = user_info["info"]["email"]
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?, :current_foodbank

    private
        def current_user
            User.find_by_id(session[:user_id]) if logged_in?
        end

        def logged_in?
            !!session[:user_id]
        end

        def current_foodbank
            FoodBank.find_by(params[:food_bank_id])
        end
end

app/controllers/food_banks_controller.rb
class FoodBanksController < ApplicationController


end

app/controllers/orders_as_admin_controller.rb
class OrdersAsAdminController < ApplicationController

    def index
        if params[:food_bank_id]
            @orders = Order.where(food_bank_id: params[:food_bank_id])
        else
            @orders = Order.all
        end
    end

    def new
        if params[:food_bank_id]
            @order = Order.new(food_bank_id: params[:food_bank_id])
        else
            @order = Order.new
        end
    end

    def create
        @order = Order.create(order_params)
        if @order.save
            binding.pry
            redirect_to food_bank_orders_as_admin_index_path(current_foodbank)
        else
            flash[:notice] = "Missing item(s) from order, fill in all options"
            render :new
        end
    end

    def show
        @order = Order.find_by_id(params[:id])
    end

    private

        def order_params
            params.require(:order).permit(:user_id, :food_bank_id, :protein, :vegetable, :fruit, :grain, :dairy, :dessert)
        end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, except: [:index, :new, :create]

    def index
        @orders = current_user.orders
    end

    def new
        @order = Order.new
    end

    def show
        if current_user == @order.user
            render :show
        else
            redirect_to root_path
        end
    end

    def create
        # @order = Order.create(order_params)
        @order = current_user.orders.build(order_params)
        if @order.save
            redirect_to user_orders_path(current_user)
        else
            flash[:notice] = "Missing item(s) from order, fill in all options"
            render :new
        end
    end

    def edit
        if current_user == @order.user
            render :edit
        else
            redirect_to root_path
        end
    end

    def update
        if current_user == @order.user 
            if @order.update(order_params)
                redirect_to user_order_path(current_user, @order)
            else
                render :edit
            end
        else
            redirect_to root_path
        end
    end

    def destroy
        if current_user == @order.user
            @order.destroy
            redirect_to user_orders_path(current_user)
        else
            redirect_to root_path
        end
    end

    private

        def set_order
            @order = Order.find_by_id(params[:id])
        end

        def order_params
            params.require(:order).permit(:user_id, :food_bank_id, :protein, :vegetable, :fruit, :grain, :dairy, :dessert)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.find_by_email(user_params[:email])

        if @user && @user.authenticate(user_params[:password])
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash[:notice] = "Invalid email or password"
            redirect_to "/login"
        end
    end

    def facebook
        user = User.find_or_create_from_omniauth(auth)
        session[:user_id] = user.id
    
        redirect_to root_path
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    private
        def user_params
            params.require(:user).permit(:email, :password)
        end

        def auth
            request.env["omniauth.auth"]
        end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash.now[:error] = @user.errors.full_messages
            render :new
        end
    end

    private
        def user_params
            params.require(:user).permit(:email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_banks_helper.rb
module FoodBanksHelper
end

app/helpers/orders_as_admin_helper.rb
module OrdersAsAdminHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="teal darken-4">
  <div class="container">
    <%# <%= link_to "Home", root_path, class: "brand-logo" %> %>
    <ul class="right">
      <li><%= link_to "View Orders", orders_path %></li>
      <li><%= link_to "Create Order", new_order_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioProjectRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
  </head>

  <body>
  
    <% if flash[:error] %>
        <% flash[:error].each do |error| %>
          <div>
            <%= error %>
          </div>
        <% end %>
      <% end %>
    <% if flash[:notice] %>
        <%= flash[:notice] %>
    <% end %>
    <nav class="orange accent-2">
      <div class="container">
        <ul class="right">
          <li><%= link_to "Home", root_path %></li>

          <% unless logged_in? %>
            <li><%= link_to "Signup", signup_path %></li>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to 'Log in with Facebook!', '/auth/facebook' %></li>
          <% else %>
          <li><%= link_to "Orders", user_orders_path(current_user) %></li>
          <li><%= link_to "Create Order", new_user_order_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/landing_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioProjectRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="teal darken-4">
    <div class="container white", style="padding: 5px; margin-top 10px;">
          <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for([current_user, order]) do |f| %>
    <div>
        Select Food Bank Location <br>
        <%= f.collection_select(:food_bank_id, FoodBank.all, :id, :location) %> 
    </div><br>
    <div>
        <%= f.label :protein %>
        <div>
        <%= f.text_field :protein, :class => "new-order", :placeholder => "Enter Protein"  %>
        </div>
    </div><br>
    <div>
        <%= f.label :vegetable %>
        <%= f.text_field :vegetable, :class => "new-order", :placeholder => "Enter Vegetable" %>
    </div><br>
    <div>
        <%= f.label :fruit %>
        <%= f.text_field :fruit, :class => "new-order", :placeholder => "Enter Fruit"  %>
    </div><br>
    <div>
        <%= f.label :grain %>
        <%= f.text_field :grain, :class => "new-order", :placeholder => "Enter Grain"  %>
    </div><br>
    <div>
        <%= f.label :dairy %>
        <%= f.text_field :dairy, :class => "new-order", :placeholder => "Enter Dairy"  %>
    </div><br>
    <div>
        <%= f.label :dessert %>
        <%= f.text_field :dessert, :class => "new-order", :placeholder => "Dessert"  %>
    </div><br>

    <%= f.submit button_name %>
    
<% end %>

  <script> $(document).ready(function(){
    $('select').formSelect();
  }); </script>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render partial: "orders/form", locals: {order: @order, button_name: "Edit Order"} %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<ul>
    <% @orders.each do |order| %>
        <div>
            <%= link_to "Go to order", user_order_path(current_user, order.id) %>
            <p><%= order.protein %></p>
            <p><%= order.vegetable %></p>
            <p><%= order.fruit %></p>
            <p><%= order.grain %></p>
            <p><%= order.dairy %></p>
            <p><%= order.dessert %></p>
        </div>
</ul>

<% end %>

app/views/orders/new.html.erb
<h1>Create Order</h1>

<%= render partial: "orders/form", locals: {order: @order, button_name: "Create Order"} %>

app/views/orders/show.html.erb
<h1>Your order</h1>


<p>Proten: <%= @order.protein %></p>
<p>Vegetable: <%= @order.vegetable %></p>
<p>Fruit: <%= @order.fruit %></p>
<p>Grain: <%= @order.grain %></p>
<p>Dairy: <%= @order.dairy %></p>
<p>Dessert: <%= @order.dessert %></p>

<%= link_to "Edit Order", edit_user_order_path(@order) %> | <%= link_to "Delete Order", user_order_path(@order), method: "delete" %>

app/views/orders_as_admin/index.html.erb
<h1>Orders</h1><br>
    <div>
        <ul>
            <li><%= link_to "Admin - Add Order", new_orders_as_admin_path %></li>
            <li><%= link_to "Admin - Add Order for FoodBank 1", new_food_bank_orders_as_admin_path(1) %></li>
            <li><%= link_to "Admin - Add Order for FoodBank 2", new_food_bank_orders_as_admin_path(2) %></li>
            <li><%= link_to "Admin - Add Order for FoodBank 3", new_food_bank_orders_as_admin_path(3) %></li>
            <li><%= link_to "Admin - Add Order for FoodBank 4", new_food_bank_orders_as_admin_path(4) %></li>
            <li><%= link_to "Admin - Add Order for FoodBank 5", new_food_bank_orders_as_admin_path(5) %></li>
        <ul>
    </div>

<ul>
    <% @orders.each do |order| %>
        <div>
            <%= link_to "Go to order", orders_as_admin_path(order) %>
            <p><%= order.user_id %></p>
            <p><%= order.protein %></p>
            <p><%= order.vegetable %></p>
            <p><%= order.fruit %></p>
            <p><%= order.grain %></p>
            <p><%= order.dairy %></p>
            <p><%= order.dessert %></p>
        </div>
    <% end %>
</ul>

app/views/orders_as_admin/new.html.erb
<%= form_for(@order, url: orders_as_admin_index_path) do |f| %>
    <div>
        Select Food Bank Location <br>
        <%= f.collection_select(:food_bank_id, FoodBank.all, :id, :location) %> 
    </div><br>
    <div>
        Select User for Order <br>
        <% User.all.each do |user| %>
            <p>
                <label>
                    <%= f.radio_button(:user_id, user.id) %>
                    <span><%= user.email %></span>
                </label>
            </p>
        <% end %>
    </div>
    <div>
        <%= f.label :protein %>
        <div>
        <%= f.text_field :protein, :class => "new-order", :placeholder => "Enter Protein"  %>
        </div>
    </div><br>
    <div>
        <%= f.label :vegetable %>
        <%= f.text_field :vegetable, :class => "new-order", :placeholder => "Enter Vegetable" %>
    </div><br>
    <div>
        <%= f.label :fruit %>
        <%= f.text_field :fruit, :class => "new-order", :placeholder => "Enter Fruit"  %>
    </div><br>
    <div>
        <%= f.label :grain %>
        <%= f.text_field :grain, :class => "new-order", :placeholder => "Enter Grain"  %>
    </div><br>
    <div>
        <%= f.label :dairy %>
        <%= f.text_field :dairy, :class => "new-order", :placeholder => "Enter Dairy"  %>
    </div><br>
    <div>
        <%= f.label :dessert %>
        <%= f.text_field :dessert, :class => "new-order", :placeholder => "Dessert"  %>
    </div><br>

    <%= f.submit %>
    
<% end %>

  <script> $(document).ready(function(){
    $('select').formSelect();
  }); </script>

  

app/views/orders_as_admin/show.html.erb
<h1>Your order</h1>


<p>Proten: <%= @order.protein %></p>
<p>Vegetable: <%= @order.vegetable %></p>
<p>Fruit: <%= @order.fruit %></p>
<p>Grain: <%= @order.grain %></p>
<p>Dairy: <%= @order.dairy %></p>
<p>Dessert: <%= @order.dessert %></p>

<%#= link_to "Edit Order", edit_user_order_path(@order) %> | <%#= link_to "Delete Order", user_order_path(@order), method: "delete" %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user, url: signup_path do |f| %>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div><br>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <%= f.submit "Signup" %>
<% end %>